name: server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  socket_io: ^1.0.0
  common:
    path: ../common

dev_dependencies:
  pedantic: ^1.10.0
